#
# ### Continueous Deployment
#
# Ensure that code successfully builds passes tests, and deploy it
#
# Required parameters
#   - azureServiceConnectionName: Service connection to use for deployment
#   - azureAppServiceName: Name of app service
#

trigger:
  branches:
    include:
    - main
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: vars/vars-all.yaml
- template: vars/vars-cd.yaml

steps:
- template: steps/git-checkout.yaml
- template: steps/build-test.yaml
- template: steps/publish.yaml
- template: steps/deploy-appservice.yaml
